version: "3.8"

networks:
  netPRO290.1:
    external: false

services:
  eureka.c:
    container_name: eureka.c
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"
    networks:
      - netPRO290.1
  
  inventorysqldb.c:
    container_name: inventorysqldb.c
    build:
      context: ./DBSetup/InventorySetup/
      dockerfile: InventorySQL.dockerfile
    #image: sqlserver.c:1
    # the old way when I wasn't using a dockerfile
    image: inventorysqldb.c
    ports:
      - '1433:1433'
    networks:
      - netPRO290.1
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=\\Secure@Password421
  
  userinfosqldb.c:
    container_name: userinfosqldb.c
    build:
      context: ./DBSetup/UserInfoSetup/
      dockerfile: UserInfoSQL.dockerfile
    #image: sqlserver.c:1
    # the old way when I wasn't using a dockerfile
    image: userinfosqldb.c
    ports:
      - '1434:1433'
    networks:
      - netPRO290.1
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=\\Secure@Password421
  
  dotnet-api-card.1.c:
    container_name: dotnet-api-card.1.c
    build:
      context: ./CardAPI/
      dockerfile: Dockerfile
    image: dotnet-api-card.1.c:1
    ports:
      - "9501:80"
    networks:
      - netPRO290.1
    depends_on:
      - userinfosqldb.c
      - eureka.c
    
  dotnet-api-user.1.c:
    container_name: dotnet-api-user.1.c
    build: 
      context: ./UserAPI/
      dockerfile: Dockerfile
    image: dotnet-api-user.1.c:1
    ports:
      - "9502:80"
    networks:
      - netPRO290.1
    depends_on:
      - userinfosqldb.c
      - eureka

  dotnet-api-user.2.c:
    container_name: dotnet-api-user.2.c
    build: 
      context: ./UserAPI/
      dockerfile: Dockerfile
    image: dotnet-api-user.1.c:1
    ports:
      - "9503:80"
    networks:
      - netPRO290.1
    depends_on:
      - userinfosqldb.c
      - eureka

  dotnet-api-inventory.1.c:
    container_name: dotnet-api-inventory.1.c
    build:
      context: ./InventoryAPI/
      dockerfile: Dockerfile
    image: dotnet-api-inventory.1.c:1
    ports:
      - "9504:80"
    networks:
      - netPRO290.1
    depends_on:
      - inventorysqldb.c
      - eureka.c

  dotnet-api-inventory.2.c:
    container_name: dotnet-api-inventory.2.c
    build:
      context: ./InventoryAPI/
      dockerfile: Dockerfile
    image: dotnet-api-inventory.1.c:1
    ports:
      - "9505:80"
    networks:
      - netPRO290.1
    depends_on:
      - inventorysqldb.c
      - eureka.c

  dotnet-api-cart.1.c:
    container_name: dotnet-api-cart.1.c
    build:
      context: ./CartAPI/
      dockerfile: Dockerfile
    image: dotnet-api-cart.1.c:1
    ports:
      - "9506:80"
    networks:
      - netPRO290.1
    depends_on:
      - eureka.c

  dotnet-api-cart.2.c:
    container_name: dotnet-api-cart.2.c
    build:
      context: ./CartAPI/
      dockerfile: Dockerfile
    image: dotnet-api-cart.1.c:1
    ports:
      - "9506:80"
    networks:
      - netPRO290.1
    depends_on:
      - eureka.c

  python-api-email.1.c:
    container_name: python-api-email.1.c
    build: 
      context: ./EmailAPI/
      dockerfile: Dockerfile
    image: python-api-email.1.c:1
    ports:
      - "5000:5000"
    networks:
      - netPRO290.1
    depends_on:
      - eureka.c

  apigateway.c:
    container_name: apigateway.c
    build:
      context: ./GatewayDemo/
      dockerfile: 2.dockerfile
    image: apigateway.c:1    
    ports:
      - "8888:8888"
    networks:
      - netPRO290.1      
    depends_on:
      - eureka.c
