CREATE DATABASE UserSQLDB

CREATE TABLE userTable (
    Id BIGINT PRIMARY NOT NULL,
    Pass NVARCHAR(MAX),
    Username NVARCHAR(MAX),
    FName NVARCHAR(MAX),
    LName NVARCHAR(MAX),
    Email NVARCHAR(MAX)
);