server:
  port: 8888

eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka.c:8761/eureka

spring:
  application:
    name: gateway-service-sen300
  cloud:
    gateway:
      routes:
      #only to be touched when new apis need to be added.
      - id: userService
        uri: lb://user-api
        predicates:
        - Path=/users/**
        filters:
         - RewritePath=/users/(?<segment>.*), /$\{segment}
            
      - id: cartService
        uri: lb://cart-api
        predicates:
        - Path=/cart/**
        filters:
         - RewritePath=/cart/(?<segment>.*), /$\{segment}
    
      - id: inventoryService
        uri: lb://inventory-api
        predicates:
        - Path=/inventory/**
        filters:
          - RewritePath=/inventory/(?<segment>.*), /$\{segment}

      - id: cardService
        uri: lb://card-api
        predicates:
        - Path=/creditCard/**
